version: '3.3'

networks:
  nextcloud_network:
    external: false

services:
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ins4neL0n6P4$swOrD_Pl34$e-cHanGeIt!!
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: SecR37_My$QL--PA$$w0rD--cHanGeIt
    volumes:
      - ./data_db:/var/lib/mysql
    networks:
      - nextcloud_network
      
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_app
    depends_on:
      - db
    restart: always
    ports:
      - 0.0.0.0:8081:80
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: SecR37_My$QL--PA$$w0rD--cHanGeIt
      MYSQL_HOST: db:3306
      REDIS_HOST: redis
    volumes:
      - ./data_nextcloud/apps:/var/www/html/custom_apps
      - ./data_nextcloud/config:/var/www/html/config
      - ./data_nextcloud/data:/var/www/html/data
      - ./data_nextcloud/themes:/var/www/html/themes
    networks:
      - nextcloud_network
  
  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    volumes:
      - /docker/nextcloud/redis:/data
    networks:
      - nextcloud_network
    restart: always
